services:
  - type: web
    name: warehouse-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
